language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mohitchaudhary17/multi-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mohitchaudhary17/multi-test npm run test -- --coverage

after_success:
  - docker build -t mohitchaudhary17/multi-client ./client
  - docker build -t mohitchaudhary17/multi-nginx ./nginx
  - docker build -t mohitchaudhary17/multi-server ./server
  - docker build -t mohitchaudhary17/multi-worker ./worker

  # Login into docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push the images in docker hub
  - docker push mohitchaudhary17/multi-client
  - docker push mohitchaudhary17/multi-nginx
  - docker push mohitchaudhary17/multi-server
  - docker push mohitchaudhary17/multi-worker

deploy:
  region: "ap-south-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-758738999818"
  bucket_path: "docker-multi"
  access_key_id: $AWS_ACCESS_KEY
  secure_access_key: $AWS_SECRET_KEY
