version: '3'
services:
  client:
    image: mohitchaudhary17/multi-client
    mem_limit: 128m
    hostname: client
  server:
    image: mohitchaudhary17/multi-server
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: mohitchaudhary17/multi-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "mohitchaudhary17/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
